# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: coverage

on:
    push:
        branches:
            - main

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install
              run: |
                    npm i
            - name: Cov Badge And Publish
              uses: nolleh/jest-badge-deploy-action@latest
